---
- name: Deploy reminder based on environment type
  hosts: all
  become: true
  gather_facts: false
  vars:
    stand_type: "{{ lookup('env','STAND_TYPE') | default('test') }}"  # переменная окружения или заданная по умолчанию

  pre_tasks:
    - name: Set target group dynamically and directories dynamically
      set_fact:
        target_group: "{% if stand_type == 'prom' %} telebot_host {% else %} test_host {% endif %}"
        deploy_dir: "{% if stand_type == 'prom' %} /root/deploy {% else %} /home/greenbec/deploy {% endif %}"
        dest_dir:  "{% if stand_type == 'prom' %} /root/reminder {% else %} /home/greenbec/reminder {% endif %}"
        git_branch: "{% if stand_type == 'prom' %} master {% else %} develop {% endif %}"

    - name: Debugging multiple variables
      debug:
        msg: "target_group={{ target_group }} | deploy_dir={{ deploy_dir }} | dest_dir={{ dest_dir }}"

  roles:
    - role: reminder
      delegate_to: "{{ groups[target_group][0] }}"  # делегируем выполнение первому хосту выбранной группы
      run_once: yes