- name: Install zabbix
  hosts: zabbix 
  become: true

  tasks:

    - name: git
      apt:
        name: git 
        state: present

    - name: install zabbix-server
      apt:
        name: zabbix-server-mysql
        state: present

