- name: Install zabbix
  hosts: zabbix 
  become: true

  tasks:

    - name: git
      apt:
        name: git 
        state: present

    - name: install zabbix-server
      apt:
        name: zabbix-server-mysql
        state: present

    - name: copy file create_db.sql
      copy:
        src: /home/rem/Ansible/create_db.sql
        dest: /home/"{{user}}"/

    - name: create db
      shell: sudo mysql < /home/"{{user}}"/create_db.sql

